name: fastbook
channels:
    - fastai
    - pytorch
    - defaults
dependencies:
  - python>=3.6
  - pytorch>=1.6.0
  - torchvision>=0.7
  - fastcore>=1.0.0
  - fastai>=2.0.0
  - fastprogress>=0.2.4
  - matplotlib
  - pandas
  - requests
  - pyyaml
  - pillow
  - scikit-learn
  - scipy
  - spacy
  - notebook
  - pip
  - pip:
    - graphviz
    - ipywidgets
    - fastbook
    - voila==0.2.4
    - azure-cognitiveservices-search-imagesearch
    - sentencepiece
    - googledrivedownloader
